# Generated by Django 4.0.4 on 2022-04-17 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, verbose_name='Código')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('symbol', models.CharField(max_length=255, verbose_name='Símbolo')),
            ],
            options={
                'verbose_name': 'Moeda',
                'verbose_name_plural': 'Moedas',
            },
        ),
        migrations.CreateModel(
            name='RateCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(verbose_name='Valor')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotation.currency', verbose_name='Moeda')),
            ],
            options={
                'verbose_name': 'Proporção da moeda',
                'verbose_name_plural': 'Proporções das moedas',
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotation.currency', verbose_name='Moeda base')),
                ('rate', models.ManyToManyField(to='quotation.ratecurrency', verbose_name='Proporção da moeda')),
            ],
            options={
                'verbose_name': 'Proporção',
                'verbose_name_plural': 'Proporções',
            },
        ),
    ]
