version: "3.9"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_NAME: "quotationdb"
      POSTGRES_USER: "quotation"
      POSTGRES_PASSWORD: "quotation_password"
    ports:
      - "5432:5432"
    networks:
      - quotation_net
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "angeloasiqueira@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "pgadmin"
    ports:
      - "16543:80"
    depends_on:
      - postgres
    networks:
      - quotation_net

networks:
  quotation_net:
    driver: bridge
