# Generated by Django 3.2.9 on 2022-05-01 18:05

from django.db import migrations

from core.models import Settings


def set_quotation_api_url_setting(apps, schema_editor):
    settings = Settings.get_solo()
    settings.quotation_api = 'https://api.vatcomply.com/'
    settings.save()    


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(set_quotation_api_url_setting),
    ]
